### ISSUE TITLE
[meta] .ini vs. .yaml and tune vs. wandb debate

### ISSUE THREAD

**Issue by quinn-dougherty** [RedTachyon/cpr_reputation#49]
quinn: `.ini` regime is good enough to rocknroll
ariel: a `.yaml` regime allows us to move in the direction of `tune` and/or `wandb`

**Comment by RedTachyon** [comment]
I have two reasons against .ini:
- Flexibility - with ini, each parameter has to be defined in the parser and In the actual ini file. With a yaml, you should be able to just put whatever parameters into the .yaml and they'll get loaded, and the rest will be implicitly set to default values in rllib
- Reproducibility - if you add a new parameter to the ini parser, you have to go back to the old .ini files and amend them so that it still works. With yaml, you just add another parameter to the .yaml, but the old ones will still work
